name: unit_tests
on: [push, pull_request]
jobs:
    run-tests-x64:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1
              with:
                  python-version: '3.10'
                  architecture: 'x64'
            - name: Setup dependencies
              run: |
                  pip install -r test_requirements.yml
            - name: Run tests
              run: |
                  make test
